version: "3"
services:
  expert-bot:
    container_name: expert-bot
    build: bot
    restart: always
    volumes:
      - ./bot/:/application/
    env_file:
      - .env
    networks:
      - app

volumes:
  db-data:
    driver: local

networks:
  app:
    driver: bridge